services:
  data-migration-application:
    build: .
    ports:
      - "8001:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/data-migration
    depends_on:
      - db
      - minio

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
#    volumes:
#      - ./data-migration.sql:/docker-entrypoint-initdb.d/data-migration.sql

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio-data/ --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio-data/:/minio-data/
